Scripts: 'gl-port' Add naive error checks.
Signed-off-by: Lewis Cook <vulcan@wired.sh>

diff --git a/.scripts/gl-port b/.scripts/gl-port
--- a/.scripts/gl-port
+++ b/.scripts/gl-port
@@ -21,6 +21,7 @@ readonly WC=/usr/bin/wc
 readonly XARGS=/usr/bin/xargs
 
 readonly BLUE="\033[34m"
+readonly RED="\033[31m"
 readonly RESET="\033[0m"
 
 usage() {
@@ -56,38 +57,75 @@ print_info() {
 	fi
 }
 
+print_error() {
+	if [ -z "${SHOW}" ]; then
+		printf "ERROR: %b%s%b\n" "${RED}" "$*" "${RESET}"
+	fi
+	exit 1
+}
+
 if [ -z "${UPDATE}" ] && [ -z "${ADD}" ] || [ -z "${PORT}" ] || [ -z "${CATEGORY}" ]; then
 	usage
 fi
 
 if [ ! -d "${DIR}" ]; then
-	${ECHO} "'${DIR}' is not a valid directory"
-	exit 1
+	print_error "'${DIR}' is not a valid directory"
 fi
 
 readonly PORTPATH="${DIR}/${CATEGORY}/${PORT}"
 if [ "${UPDATE}" = true ] && [ ! -d "${PORTPATH}" ]; then
-	${ECHO} "'${CATEGORY}/${PORT}' is not a valid port"
-	exit 1
+	print_error "'${CATEGORY}/${PORT}' is not a valid port"
 fi
 
 readonly TMP=$(${MKTEMP} -d)
+cleanup() {
+	print_info "Cleaning up temp directory"
+	${RM} -rf "${TMP}"
+	exit 0
+}
+
+readonly RC=${TMP}/status
+${ECHO} 0 > "${RC}"
+
 readonly DIFF="${TMP}/${PORT}.diff"
 (
 	cd "${TMP}" || exit
 
 	print_info "Checking out latest SVN revision @ ${CATEGORY}/${PORT}"
-	${SVN} checkout --depth empty "https://svn.FreeBSD.org/ports/head/${CATEGORY}/${PORT}" . 1> /dev/null
+	${SVN} checkout --depth empty "https://svn.FreeBSD.org/ports/head/${CATEGORY}/${PORT}" . > /dev/null 2>&1
 
+	STATUS=$?
+	if [ "${STATUS}" != 0 ]; then
+		${ECHO} ${STATUS} > "${RC}"
+		print_error "Unable to checkout, is '${PORT}/${CATEGORY}' a valid port?"
+	fi
+
+	# shellcheck disable=SC2030
 	REVISION=0
 	if [ "${UPDATE}" = true ]; then
-		REVISION=$(${SVN} log -l"${LIMIT}" --xml | ${XQ} -r '.[].logentry['"${ENTRY}"']."@revision"')
-		${ECHO} "${REVISION}" | ${XARGS} -I % svn diff -r %:HEAD > "${DIFF}"
+		REVISION=$(${SVN} log -l"${LIMIT}" --xml 2> /dev/null | ${XQ} -r '.[].logentry['"${ENTRY}"']."@revision"' 2> /dev/null)
+		${ECHO} "${REVISION}" | ${XARGS} -I % svn diff -r %:HEAD 2> /dev/null > "${DIFF}"
 	else
+		if [ -d "${PORTPATH}" ]; then
+			${ECHO} 1 > "${RC}"
+			print_error "'${CATEGORY}/${PORT}' already exists in repository"
+		fi
+
 		${SVN} diff -r 0:HEAD > "${DIFF}"
 	fi
+
+	STATUS=$?
+	if [ "${STATUS}" != 0 ]; then
+		${ECHO} ${STATUS} > "${RC}"
+		print_error "Could not generate patch"
+	fi
+
 	print_info "Generating diff via commit(s) ${REVISION}:HEAD"
 )
+
+if [ "$(${CAT} "${RC}")" != 0 ]; then
+	cleanup
+fi
 
 if [ "${SHOW}" = true ]; then
 	${CAT} "${DIFF}"
@@ -106,11 +144,13 @@ fi
 )
 
 if [ "${ADD}" = true ]; then
+	# shellcheck disable=SC2031
 	readonly REVISION=$(cd "${TMP}" && ${SVN} log -r 0:HEAD -l1 --xml | ${XQ} -r '.log.logentry."@revision"')
 else
 	readonly REVISION=$(cd "${TMP}" && ${SVN} log -l1 --xml | ${XQ} -r '.log.logentry."@revision"')
 fi
 readonly PORTSET="https://svnweb.freebsd.org/ports?view=revision&revision=${REVISION}"
+# shellcheck disable=SC2016
 readonly VERSION=$(${AWK} '/(DIST|PORT)VERSION=.*/{print $2}' "${PORTPATH}/Makefile")
 readonly SIGNED=$(${CAT} "/usr/home/${USER}/.gitmessage")
 readonly FULLPORT="${CATEGORY}/${PORT}"
@@ -136,6 +176,7 @@ readonly NAME=$(${GIT} config user.name)
                              ${SIGNED}"
 
 	${ECHO}
+	# shellcheck disable=SC2039
 	read -rp "Push commit to master? (yes/no) [no]: " OPTION
 	OPTION=$(${ECHO} "${OPTION}" | ${TR} "[:upper:]" "[:lower:]")
 	if [ "${OPTION}" = yes ] || [ "${OPTION}" = y ]; then
@@ -144,5 +185,4 @@ readonly NAME=$(${GIT} config user.name)
 	${ECHO}
 )
 
-print_info "Cleaning up temp directory"
-${RM} -rf "${TMP}"
+cleanup
